import { Router } from "express";
import { asyncHandler } from "../middleware/errors.js";
import { requireAuth, requireRole, optionalAuth } from "../middleware/auth.js";
import * as products from "../controllers/products.js";
import * as catalog from "../controllers/catalog.js";
import * as auth from "../controllers/auth.js";
import * as customers from "../controllers/customers.js";
import * as orders from "../controllers/orders.js";
import * as admin from "../controllers/admin.js";
import { prisma } from "../config/prisma.js";
import { z } from "zod";

const router = Router();
const protect = requireAuth;
const adminOnly = [protect, requireRole("ADMIN")];
router.get("/products", asyncHandler(products.index));
router.get("/products/slug/:slug", asyncHandler((req, res) => products.show({ ...req, params: { id: req.params.slug } }, res)));
router.get("/products/:id", asyncHandler(products.show));
router.get("/categories", asyncHandler(catalog.categories));
router.get("/categories/:id", asyncHandler(catalog.category));
router.get("/brands", asyncHandler(catalog.brands));
router.post("/cart", asyncHandler(async (req, res) => {
  const { items } = z.object({ items: z.array(z.object({ productId: z.coerce.number().int().positive().optional(), id: z.coerce.number().int().positive().optional(), quantity: z.coerce.number().int().min(1).max(100) }).refine(i => i.productId || i.id)).min(1) }).parse(req.body);
  const parsed = items.map(i => ({ id: i.productId || i.id, quantity: i.quantity }));
  const products = await prisma.product.findMany({ where: { id: { in: parsed.map(i => i.id) }, status: "PUBLISHED", purchasable: true }, include: { images: { orderBy: { position: "asc" }, take: 1 } } });
  const byId = new Map(products.map(p => [p.id, p]));
  if (parsed.some(i => !byId.has(i.id))) return res.status(400).json({ success: false, message: "One or more products are unavailable" });
  const lines = parsed.map(i => { const p = byId.get(i.id); const price = Number(p.salePrice ?? p.price); if (p.stockStatus === "OUT_OF_STOCK" || (p.manageStock && p.stockQuantity != null && p.stockQuantity < i.quantity)) throw Object.assign(new Error(`${p.name} does not have enough stock`), { status: 409 }); return { productId: p.id, name: p.name, quantity: i.quantity, unitPrice: price, total: price * i.quantity, image: p.images[0]?.url || null }; });
  res.json({ success: true, data: { items: lines, subtotal: lines.reduce((sum, item) => sum + item.total, 0) } });
}));
router.post("/events", optionalAuth, admin.trackEvent);
router.post("/inquiries", asyncHandler(async (req, res) => {
  const body = z.object({ name: z.string().trim().min(1).max(150), email: z.string().email().max(254), message: z.string().trim().min(5).max(5000) }).parse(req.body);
  const row = await prisma.inquiry.create({ data: body });
  res.status(201).json({ success: true, message: "Thank you. Your message has been received.", data: { id: row.id } });
}));
router.post("/auth/register", auth.register);
router.post("/auth/login", auth.login);
router.post("/auth/forgot-password", auth.forgotPassword);
router.post("/auth/reset-password", auth.resetPassword);
router.get("/auth/me", protect, auth.me);
router.get("/customers/me", protect, auth.me);
router.patch("/customers/me", protect, customers.updateMe);
router.put("/customers/me", protect, customers.updateMe);
router.get("/customers/me/addresses", protect, customers.getAddresses);
router.put("/customers/me/addresses/:type", protect, customers.saveAddress);
router.post("/customers/me/password", protect, customers.changePassword);
router.get("/customers/me/orders", protect, customers.orders);
router.post("/orders", optionalAuth, orders.create);
router.get("/orders", protect, orders.listMine);
router.get("/orders/:id", protect, orders.showMine);
router.post("/reviews", asyncHandler(async (req, res) => {
  const { productId, reviewer, review, rating } = z.object({ productId: z.coerce.number().int().positive(), reviewer: z.string().trim().min(1).max(150), reviewer_email: z.string().email().optional(), review: z.string().trim().min(1).max(5000), rating: z.coerce.number().int().min(1).max(5) }).parse(req.body);
  const product = await prisma.product.findUnique({ where: { id: productId } });
  if (!product) return res.status(404).json({ success: false, message: "Product not found" });
  const row = await prisma.review.create({ data: { productId: product.id, reviewer, review, rating } });
  res.status(201).json({ success: true, data: row, message: "Review submitted for moderation" });
}));
router.get("/reviews", asyncHandler(async (req, res) => {
  const rows = await prisma.review.findMany({ where: { approved: true }, take: 6, orderBy: { createdAt: "desc" } });
  res.json({ success: true, data: rows.map(r => ({ id: r.id, product_id: r.productId, reviewer: r.reviewer, review: r.review, rating: r.rating, date_created: r.createdAt })) });
}));
router.get("/products/:id/reviews", asyncHandler(async (req, res) => {
  const productId = Number(req.params.id);
  const rows = await prisma.review.findMany({ where: { productId, approved: true }, take: 6, orderBy: { createdAt: "desc" } });
  res.json({ success: true, data: rows.map(r => ({ id: r.id, product_id: r.productId, reviewer: r.reviewer, review: r.review, rating: r.rating, date_created: r.createdAt })) });
}));
router.get("/admin/dashboard", ...adminOnly, admin.dashboard);
router.get("/admin/cart-activity", ...adminOnly, admin.cartActivity);
router.get("/admin/products", ...adminOnly, admin.products);
router.post("/admin/products", ...adminOnly, admin.createProduct);
router.patch("/admin/products/:id", ...adminOnly, admin.updateProduct);
router.delete("/admin/products/:id", ...adminOnly, admin.deleteProduct);
router.get("/admin/categories", ...adminOnly, admin.categories);
router.post("/admin/categories", ...adminOnly, admin.createCategory);
router.patch("/admin/categories/:id", ...adminOnly, admin.updateCategory);
router.delete("/admin/categories/:id", ...adminOnly, admin.deleteCategory);
router.get("/admin/customers", ...adminOnly, admin.customers);
router.post("/admin/users", ...adminOnly, admin.createUser);
router.patch("/admin/users/:id", ...adminOnly, admin.updateUser);
router.delete("/admin/users/:id", ...adminOnly, admin.deleteUser);
router.get("/admin/orders", ...adminOnly, admin.orders);
router.patch("/admin/orders/:id/status", ...adminOnly, admin.setOrderStatus);
router.get("/admin/reviews", ...adminOnly, admin.reviews);
router.patch("/admin/reviews/:id/approval", ...adminOnly, admin.setReviewApproval);
router.get("/admin/inquiries", ...adminOnly, admin.inquiries);
router.patch("/admin/inquiries/:id", ...adminOnly, admin.updateInquiry);
export default router;
